// This file is auto-generated by @hey-api/openapi-ts

import type { Client, ClientMeta, Options as Options2, RequestResult, ServerSentEventsResult, TDataShape } from './client';
import { client } from './client.gen';
import type { BookIndex2Data, BookIndex2Errors, BookIndex2Responses, BookIndexData, BookIndexErrors, BookIndexResponses, BooksData, BooksResponses, BookText2Data, BookText2Errors, BookText2Responses, BookTextData, BookTextErrors, BookTextResponses, ChapterAudio2Data, ChapterAudio2Errors, ChapterAudio2Responses, ChapterAudioData, ChapterAudioErrors, ChapterAudioResponses, ChapterData, ChapterErrors, ChapterHls2Data, ChapterHls2Errors, ChapterHls2Responses, ChapterHlsData, ChapterHlsErrors, ChapterHlsResponses, ChapterManifest2Data, ChapterManifest2Errors, ChapterManifest2Responses, ChapterManifestData, ChapterManifestErrors, ChapterManifestResponses, ChapterResponses, ChaptersBuildData, ChaptersBuildErrors, ChaptersBuildResponses, ChaptersCancelData, ChaptersCancelResponses, ChaptersListData, ChaptersListResponses, ChaptersRenderData, ChaptersRenderErrors, ChaptersRenderResponses, ChunkWav2Data, ChunkWav2Errors, ChunkWav2Responses, ChunkWavData, ChunkWavErrors, ChunkWavResponses, EventsData, EventsResponse, EventsResponses, HealthzData, HealthzErrors, HealthzResponses, HlsSegment2Data, HlsSegment2Errors, HlsSegment2Responses, HlsSegmentData, HlsSegmentErrors, HlsSegmentResponses, LoadData, LoadErrors, LoadResponses, NoteData, NoteErrors, NoteResponses, OpenChapterData, OpenChapterResponses, PauseData, PauseResponses, PlayheadData, PlayheadResponses, PositionData, PositionErrors, PositionResponses, PrerenderData, PrerenderErrors, PrerenderResponses, RendererData, RendererResponses, ResumeData, ResumeResponses, StatusData, StatusResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

/**
 * The index: small (123 kB even for 1433 chapters) and always cached. It is
 * what lets the reader show a book it cannot reach.
 */
export const bookIndex = <ThrowOnError extends boolean = false>(options?: Options<BookIndexData, ThrowOnError>): RequestResult<BookIndexResponses, BookIndexErrors, ThrowOnError> => (options?.client ?? client).get<BookIndexResponses, BookIndexErrors, ThrowOnError>({ url: '/api/book.json', ...options });

/**
 * The index: small (123 kB even for 1433 chapters) and always cached. It is
 * what lets the reader show a book it cannot reach.
 */
export const bookIndex2 = <ThrowOnError extends boolean = false>(options?: Options<BookIndex2Data, ThrowOnError>): RequestResult<BookIndex2Responses, BookIndex2Errors, ThrowOnError> => (options?.client ?? client).head<BookIndex2Responses, BookIndex2Errors, ThrowOnError>({ url: '/api/book.json', ...options });

/**
 * `./books` merged with the vault's library, deduped by filename.
 */
export const books = <ThrowOnError extends boolean = false>(options?: Options<BooksData, ThrowOnError>): RequestResult<BooksResponses, unknown, ThrowOnError> => (options?.client ?? client).get<BooksResponses, unknown, ThrowOnError>({ url: '/api/books', ...options });

export const chapter = <ThrowOnError extends boolean = false>(options: Options<ChapterData, ThrowOnError>): RequestResult<ChapterResponses, ChapterErrors, ThrowOnError> => (options.client ?? client).get<ChapterResponses, ChapterErrors, ThrowOnError>({ url: '/api/chapter/{ci}', ...options });

/**
 * Every chapter of the loaded book: chunks rendered / total, whether the packed
 * m4a exists and how big it is.
 */
export const chaptersList = <ThrowOnError extends boolean = false>(options?: Options<ChaptersListData, ThrowOnError>): RequestResult<ChaptersListResponses, unknown, ThrowOnError> => (options?.client ?? client).get<ChaptersListResponses, unknown, ThrowOnError>({ url: '/api/chapters', ...options });

/**
 * Pack now what is complete, queue the rest for rendering first.
 */
export const chaptersBuild = <ThrowOnError extends boolean = false>(options: Options<ChaptersBuildData, ThrowOnError>): RequestResult<ChaptersBuildResponses, ChaptersBuildErrors, ThrowOnError> => (options.client ?? client).post<ChaptersBuildResponses, ChaptersBuildErrors, ThrowOnError>({
    url: '/api/chapters/build',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Drop chapters from the queues. An empty body clears both.
 */
export const chaptersCancel = <ThrowOnError extends boolean = false>(options: Options<ChaptersCancelData, ThrowOnError>): RequestResult<ChaptersCancelResponses, unknown, ThrowOnError> => (options.client ?? client).post<ChaptersCancelResponses, unknown, ThrowOnError>({
    url: '/api/chapters/cancel',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Queue chapters for rendering, in the order given. `pack: true` also packs
 * each one as it completes — that is what "download offline" asks for first.
 */
export const chaptersRender = <ThrowOnError extends boolean = false>(options: Options<ChaptersRenderData, ThrowOnError>): RequestResult<ChaptersRenderResponses, ChaptersRenderErrors, ThrowOnError> => (options.client ?? client).post<ChaptersRenderResponses, ChaptersRenderErrors, ThrowOnError>({
    url: '/api/chapters/render',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * chunk index -> start second for the packed chapter. Without this the m4a is
 * one opaque blob and every reading position in the book is lost.
 */
export const chapterManifest = <ThrowOnError extends boolean = false>(options: Options<ChapterManifestData, ThrowOnError>): RequestResult<ChapterManifestResponses, ChapterManifestErrors, ThrowOnError> => (options.client ?? client).get<ChapterManifestResponses, ChapterManifestErrors, ThrowOnError>({ url: '/api/chapters/{ci}.json', ...options });

/**
 * chunk index -> start second for the packed chapter. Without this the m4a is
 * one opaque blob and every reading position in the book is lost.
 */
export const chapterManifest2 = <ThrowOnError extends boolean = false>(options: Options<ChapterManifest2Data, ThrowOnError>): RequestResult<ChapterManifest2Responses, ChapterManifest2Errors, ThrowOnError> => (options.client ?? client).head<ChapterManifest2Responses, ChapterManifest2Errors, ThrowOnError>({ url: '/api/chapters/{ci}.json', ...options });

/**
 * An HLS playlist for the packed chapter, built on first request.
 *
 * This is the streaming path: iOS plays it natively in a plain `<audio>`, so the
 * OS owns buffering and segment retry — a blip re-fetches one six-second segment
 * instead of killing the whole load. The m4a stays the download format, because
 * native HLS bypasses the service worker and can never be the offline one.
 */
export const chapterHls = <ThrowOnError extends boolean = false>(options: Options<ChapterHlsData, ThrowOnError>): RequestResult<ChapterHlsResponses, ChapterHlsErrors, ThrowOnError> => (options.client ?? client).get<ChapterHlsResponses, ChapterHlsErrors, ThrowOnError>({ url: '/api/chapters/{ci}.m3u8', ...options });

/**
 * An HLS playlist for the packed chapter, built on first request.
 *
 * This is the streaming path: iOS plays it natively in a plain `<audio>`, so the
 * OS owns buffering and segment retry — a blip re-fetches one six-second segment
 * instead of killing the whole load. The m4a stays the download format, because
 * native HLS bypasses the service worker and can never be the offline one.
 */
export const chapterHls2 = <ThrowOnError extends boolean = false>(options: Options<ChapterHls2Data, ThrowOnError>): RequestResult<ChapterHls2Responses, ChapterHls2Errors, ThrowOnError> => (options.client ?? client).head<ChapterHls2Responses, ChapterHls2Errors, ThrowOnError>({ url: '/api/chapters/{ci}.m3u8', ...options });

/**
 * The packed chapter: AAC-LC mono 64 kbit/s, 24 kHz, `+faststart`. **Serves
 * byte ranges** — iOS probes with a Range before it will play anything. This is
 * the *download* format.
 */
export const chapterAudio = <ThrowOnError extends boolean = false>(options: Options<ChapterAudioData, ThrowOnError>): RequestResult<ChapterAudioResponses, ChapterAudioErrors, ThrowOnError> => (options.client ?? client).get<ChapterAudioResponses, ChapterAudioErrors, ThrowOnError>({ url: '/api/chapters/{ci}.m4a', ...options });

/**
 * The packed chapter: AAC-LC mono 64 kbit/s, 24 kHz, `+faststart`. **Serves
 * byte ranges** — iOS probes with a Range before it will play anything. This is
 * the *download* format.
 */
export const chapterAudio2 = <ThrowOnError extends boolean = false>(options: Options<ChapterAudio2Data, ThrowOnError>): RequestResult<ChapterAudio2Responses, ChapterAudio2Errors, ThrowOnError> => (options.client ?? client).head<ChapterAudio2Responses, ChapterAudio2Errors, ThrowOnError>({ url: '/api/chapters/{ci}.m4a', ...options });

/**
 * One rendered chunk. GET or HEAD; **404 means "not rendered yet", not an
 * error** — the reader polls this while the renderer catches up.
 */
export const chunkWav = <ThrowOnError extends boolean = false>(options: Options<ChunkWavData, ThrowOnError>): RequestResult<ChunkWavResponses, ChunkWavErrors, ThrowOnError> => (options.client ?? client).get<ChunkWavResponses, ChunkWavErrors, ThrowOnError>({ url: '/api/chunk/{ci}/{i}.wav', ...options });

/**
 * One rendered chunk. GET or HEAD; **404 means "not rendered yet", not an
 * error** — the reader polls this while the renderer catches up.
 */
export const chunkWav2 = <ThrowOnError extends boolean = false>(options: Options<ChunkWav2Data, ThrowOnError>): RequestResult<ChunkWav2Responses, ChunkWav2Errors, ThrowOnError> => (options.client ?? client).head<ChunkWav2Responses, ChunkWav2Errors, ThrowOnError>({ url: '/api/chunk/{ci}/{i}.wav', ...options });

export const events = <ThrowOnError extends boolean = false>(options?: Options<EventsData, ThrowOnError, EventsResponse>): Promise<ServerSentEventsResult<EventsResponses>> => (options?.client ?? client).sse.get<EventsResponses, unknown, ThrowOnError>({ url: '/api/events', ...options });

/**
 * One fMP4 segment (or the init segment) of a chapter's HLS rendition. `name`
 * is validated against `init.mp4|segNNNNN.m4s`; anything else is a 404.
 */
export const hlsSegment = <ThrowOnError extends boolean = false>(options: Options<HlsSegmentData, ThrowOnError>): RequestResult<HlsSegmentResponses, HlsSegmentErrors, ThrowOnError> => (options.client ?? client).get<HlsSegmentResponses, HlsSegmentErrors, ThrowOnError>({ url: '/api/hls/{book}/{ci}/{name}', ...options });

/**
 * One fMP4 segment (or the init segment) of a chapter's HLS rendition. `name`
 * is validated against `init.mp4|segNNNNN.m4s`; anything else is a 404.
 */
export const hlsSegment2 = <ThrowOnError extends boolean = false>(options: Options<HlsSegment2Data, ThrowOnError>): RequestResult<HlsSegment2Responses, HlsSegment2Errors, ThrowOnError> => (options.client ?? client).head<HlsSegment2Responses, HlsSegment2Errors, ThrowOnError>({ url: '/api/hls/{book}/{ci}/{name}', ...options });

/**
 * Parse an EPUB and make it the session's book. Also writes `plan.json` and the
 * text bundle, both rebuilt from scratch: re-parsing can move chunk boundaries,
 * and a stale shard would put every position in it on the wrong words.
 */
export const load = <ThrowOnError extends boolean = false>(options: Options<LoadData, ThrowOnError>): RequestResult<LoadResponses, LoadErrors, ThrowOnError> => (options.client ?? client).post<LoadResponses, LoadErrors, ThrowOnError>({
    url: '/api/load',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const note = <ThrowOnError extends boolean = false>(options: Options<NoteData, ThrowOnError>): RequestResult<NoteResponses, NoteErrors, ThrowOnError> => (options.client ?? client).post<NoteResponses, NoteErrors, ThrowOnError>({
    url: '/api/note',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Select a chapter and start rendering from a given chunk.
 *
 * The opened chunk is *guaranteed* to render: the worker renders whatever is
 * under the playhead before anything else, and this sets the playhead.
 */
export const openChapter = <ThrowOnError extends boolean = false>(options: Options<OpenChapterData, ThrowOnError>): RequestResult<OpenChapterResponses, unknown, ThrowOnError> => (options.client ?? client).post<OpenChapterResponses, unknown, ThrowOnError>({
    url: '/api/open',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Pause playback. The time you are *not* listening is exactly when the buffer
 * should grow, so this stops audio, not the renderer — unless
 * `PREFETCH_WHILE_PAUSED=0`.
 */
export const pause = <ThrowOnError extends boolean = false>(options?: Options<PauseData, ThrowOnError>): RequestResult<PauseResponses, unknown, ThrowOnError> => (options?.client ?? client).post<PauseResponses, unknown, ThrowOnError>({ url: '/api/pause', ...options });

/**
 * Report the playhead. Drags `render_idx` forward on a forward jump, never
 * backwards — anything already on disk still plays, and the worker skips files
 * that exist, so nothing is re-rendered.
 */
export const playhead = <ThrowOnError extends boolean = false>(options: Options<PlayheadData, ThrowOnError>): RequestResult<PlayheadResponses, unknown, ThrowOnError> => (options.client ?? client).post<PlayheadResponses, unknown, ThrowOnError>({
    url: '/api/playhead',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Record a position for a *named* book without loading it.
 *
 * This is what the offline queue pushes on reconnect, possibly for a book the
 * server has since swapped out. Last write wins, which is the right rule for one
 * reader on several devices. Fields not supplied are kept from the existing
 * record.
 */
export const position = <ThrowOnError extends boolean = false>(options: Options<PositionData, ThrowOnError>): RequestResult<PositionResponses, PositionErrors, ThrowOnError> => (options.client ?? client).post<PositionResponses, PositionErrors, ThrowOnError>({
    url: '/api/position',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * The old "render ahead N hours" target. Its UI is gone — the chapter manager
 * replaced it — but the endpoint stays for the CLI and anything else pointed
 * at it.
 */
export const prerender = <ThrowOnError extends boolean = false>(options: Options<PrerenderData, ThrowOnError>): RequestResult<PrerenderResponses, PrerenderErrors, ThrowOnError> => (options.client ?? client).post<PrerenderResponses, PrerenderErrors, ThrowOnError>({
    url: '/api/prerender',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Explicitly stop/start the render worker, independent of playback.
 */
export const renderer = <ThrowOnError extends boolean = false>(options: Options<RendererData, ThrowOnError>): RequestResult<RendererResponses, unknown, ThrowOnError> => (options.client ?? client).post<RendererResponses, unknown, ThrowOnError>({
    url: '/api/renderer',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const resume = <ThrowOnError extends boolean = false>(options?: Options<ResumeData, ThrowOnError>): RequestResult<ResumeResponses, unknown, ThrowOnError> => (options?.client ?? client).post<ResumeResponses, unknown, ThrowOnError>({ url: '/api/resume', ...options });

/**
 * The heartbeat. It is also how the reader notices the server came back.
 */
export const status = <ThrowOnError extends boolean = false>(options?: Options<StatusData, ThrowOnError>): RequestResult<StatusResponses, unknown, ThrowOnError> => (options?.client ?? client).get<StatusResponses, unknown, ThrowOnError>({ url: '/api/status', ...options });

/**
 * One shard: a run of whole chapters, ~1.5 MB at most. Cache every shard and
 * the whole book is readable with no network and no rendered audio; cache none
 * and the reader still lists it.
 */
export const bookText = <ThrowOnError extends boolean = false>(options: Options<BookTextData, ThrowOnError>): RequestResult<BookTextResponses, BookTextErrors, ThrowOnError> => (options.client ?? client).get<BookTextResponses, BookTextErrors, ThrowOnError>({ url: '/api/text/{s}.json', ...options });

/**
 * One shard: a run of whole chapters, ~1.5 MB at most. Cache every shard and
 * the whole book is readable with no network and no rendered audio; cache none
 * and the reader still lists it.
 */
export const bookText2 = <ThrowOnError extends boolean = false>(options: Options<BookText2Data, ThrowOnError>): RequestResult<BookText2Responses, BookText2Errors, ThrowOnError> => (options.client ?? client).head<BookText2Responses, BookText2Errors, ThrowOnError>({ url: '/api/text/{s}.json', ...options });

export const healthz = <ThrowOnError extends boolean = false>(options?: Options<HealthzData, ThrowOnError>): RequestResult<HealthzResponses, HealthzErrors, ThrowOnError> => (options?.client ?? client).get<HealthzResponses, HealthzErrors, ThrowOnError>({ url: '/healthz', ...options });
