// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

/**
 * Every error body in this API: `{"error": "..."}`, and nothing else. The
 * reader's `get()` reads exactly this field.
 */
export type ApiError = {
    error: string;
};

export type BookFile = {
    mb: number;
    name: string;
    /**
     * Absolute path on the server — what `/api/load` takes back.
     */
    path: string;
};

export type BookIndex = {
    chapters: Array<ChapMeta>;
    key: string;
    name: string;
    shards: number;
    text_bytes: number;
    title: string;
    total_min: number;
};

/**
 * One chapter the packer would not take, and why.
 *
 * The list this belongs to is the answer to the reader's oldest complaint
 * about this endpoint: a chapter that was not packable appeared in none of
 * `built`/`building`/`rendering` and so was **indistinguishable from a chapter
 * nobody asked about**. The client's only recourse was to re-ask every twenty
 * seconds and read the next `/api/chapters` poll to find out what happened.
 * With a reason per chapter it can tell "taken" from "not yet, and here is how
 * far it got", and keep the re-ask for a genuine stall.
 */
export type BuildRefusal = {
    chapter: number;
    n: number;
    /**
     * `not_rendered` — queued for rendering instead, and `rendered`/`n` say how
     * far it is. `no_chunks` — the chapter has no speakable text, so there is
     * nothing to pack, ever. `out_of_range` — no such chapter in this book.
     */
    reason: string;
    /**
     * How many of the chapter's chunks are on disk, and how many there are.
     * Both 0 for `out_of_range`.
     */
    rendered: number;
};

export type BuildResult = {
    /**
     * Complete and handed to the packer now.
     */
    building: Array<number>;
    /**
     * Already packed; nothing to do.
     */
    built: Array<number>;
    ok: boolean;
    /**
     * What was refused, and why — one entry per chapter this call did **not**
     * hand to the packer. A chapter in `rendering` appears here too, with
     * `not_rendered` and its progress: it was taken, but not for packing.
     */
    refused: Array<BuildRefusal>;
    /**
     * Not complete; queued for rendering first.
     */
    rendering: Array<number>;
};

export type CancelResult = {
    ok: boolean;
    queue: Array<number>;
};

export type ChapMeta = {
    est_min: number;
    i: number;
    n: number;
    /**
     * Which shard holds this chapter's words. Omitted entirely by `/api/load`,
     * always a number in `book.json` — never `null`, which is why the schema
     * overrides utoipa's default nullable-because-Option rendering.
     */
    shard?: number;
    title: string;
};

/**
 * A cached filesystem scan of one chapter. **Not truth** — see the module doc.
 *
 * The field names are [`crate::api::chapters::ChapterRow`]'s on purpose: this
 * table exists to answer that endpoint for a book the session has not loaded,
 * and a row that has to be renamed on the way out is a row that will eventually
 * be renamed wrongly.
 */
export type ChapterIndexRow = {
    bytes?: number | null;
    chapter: number;
    duration?: number | null;
    /**
     * Estimated spoken seconds, from the chunker's character counts.
     */
    est_s?: number | null;
    m4a: boolean;
    /**
     * Chunks in the plan.
     */
    n: number;
    /**
     * Chunk wavs that were on disk **when the scan ran**.
     */
    rendered: number;
    scanned_ms: number;
    title: string;
};

export type ChapterRow = {
    bytes: number | null;
    duration: number | null;
    /**
     * What this chapter will weigh once packed, at the server's own
     * `CHAPTER_BITRATE` — the arithmetic the client used to do with a
     * hard-coded 64 kbit/s it could not see. `bytes` is the measured size of a
     * chapter that exists; this is the estimate for one that does not, and it
     * is null only when the duration estimate itself is missing.
     */
    est_bytes: number | null;
    est_min: number | null;
    i: number;
    /**
     * Whether a *trustworthy* packed m4a exists. A manifest whose `chunks`
     * disagrees with the plan reports false: it points at the wrong words.
     */
    m4a: boolean;
    n: number;
    pack_queued: boolean;
    packing: boolean;
    /**
     * Present, and `true`, only for a chapter the server has stopped taking up
     * at startup: it was asked for, it has been picked back up by five restarts
     * without a single chunk of it landing, and something about it is not
     * working. Still wanted, no longer tried — asking for the chapter again is
     * the retry and clears this. Absent is the ordinary answer, and absent
     * rather than `false` so a 1433-row response pays nothing for it, which is
     * why it is not a plain `bool` like its three neighbours.
     */
    parked?: boolean | null;
    /**
     * Always present: a row only exists for a loaded book, and then the
     * chapter manager's three flags always have an answer.
     */
    queued: boolean;
    /**
     * How many of this chapter's chunks are on disk.
     */
    rendered: number;
    title: string;
};

export type ChapterSetBody = {
    /**
     * The book these chapters belong to. **Additive, and the one worth
     * sending**: this is the endpoint where a race costs hours. The reader
     * polls `/api/chapters`, the reader taps "download the rest", and in
     * between the watcher may have picked up an epub, the Obsidian plugin may
     * have opened something, another device may have loaded another book — and
     * 74 chapters of rendering then land on that one. Supplied and mismatched,
     * this is a **409**; omitted, it means "whatever is loaded", as before.
     */
    book?: string | null;
    chapters?: Array<number> | null;
    /**
     * `/api/chapters/build` only: rebuild even if an m4a already exists.
     */
    force?: boolean | null;
    /**
     * `/api/chapters/render` only: also pack each chapter as it completes.
     */
    pack?: boolean | null;
};

export type ChapterText = {
    chunks: Array<string>;
    i: number;
    /**
     * What lets the reader re-form real paragraphs from chunks. Additive:
     * existing clients (the Obsidian plugin) only read title + chunks.
     */
    paras: Array<number>;
    title: string;
};

export type ChaptersResult = {
    book: string | null;
    build_error?: string | null;
    /**
     * Absent only in the "no book loaded" shape; `null` when nothing is being
     * packed. The python server distinguishes those two and the reader's type
     * says `building?: number | null`, so the nesting is the contract.
     */
    building?: number | null;
    chapter?: number;
    chapters: Array<ChapterRow>;
    chapters_cap_gb?: number;
    chapters_gb?: number;
    /**
     * The window this response covers, when `?from=`/`?to=` narrowed it.
     * Additive: without the query these are 0 and the last chapter index, and
     * `chapters` is the whole book exactly as before.
     */
    from?: number;
    key: string | null;
    queue?: Array<number>;
    title: string | null;
    to?: number;
    /**
     * How many chapters the book has, whatever the window is.
     */
    total?: number;
};

export type Health = {
    book: string | null;
    build_error: string | null;
    /**
     * How many devices are holding an event stream right now.
     *
     * `live` counts subscribers to the bus; this counts the ones that said who
     * they are. The two disagreeing means something is connected that is not
     * this reader — the Obsidian plugin, a stray `curl` — which is worth being
     * able to see when a position seems to be moving on its own.
     */
    devices: number;
    /**
     * Open SSE streams.
     */
    live: number;
    model_ready: boolean;
    ok: boolean;
    packing: number | null;
    positions_dir: string;
    problems: Array<string>;
    queue: number;
    since_progress_s: number;
    stall_limit_s: number;
    status: string;
    /**
     * Whether `work/state.db` opened.
     *
     * **Not** a problem when it is false, deliberately — everything that
     * mattered before the store existed still works without it, and refusing to
     * be healthy over a degraded extra would have the watchdog restart the
     * container in a loop for a fault a restart cannot fix. It is reported
     * because the alternative is a box that quietly stops remembering standing
     * orders and answering for the library, with nothing anywhere saying so.
     */
    store: boolean;
    threads: Array<string>;
    uptime_s: number;
    /**
     * Where positions and notes are being written. `null` means the vault is
     * not mounted and they are falling back under the work dir — which is a
     * thing to *say*, not to hide: with NARRATOR_VAULT pointing at a path that
     * does not exist, the python server writes nothing, reads back `{}`, and
     * every book quietly opens at chapter one.
     */
    vault?: string | null;
};

/**
 * One book on this box.
 *
 * The counts are aggregates of that book's cached scan rows; `chapters` is what
 * the `book` table records, so a book whose plan is on disk but which has never
 * been scanned still says how long it is.
 */
export type LibraryBook = {
    /**
     * The per-chapter rows, present only for `?book=<key>&chapters=true`.
     *
     * Deliberately absent from the all-books answer: *Lord of Mysteries* alone
     * is 1433 of these, and a library response that carried them for every book
     * would be megabytes over a tunnel to answer a question about shelves.
     */
    chapter_index?: Array<ChapterIndexRow> | null;
    chapters: number;
    /**
     * The whole book's spoken length, from the chunker's character counts.
     * Null only when nothing has been scanned yet.
     */
    est_min: number | null;
    /**
     * The cache directory name — what `?book=` takes everywhere else.
     */
    key: string;
    /**
     * When this book was last opened, or null for one that has only ever been
     * found on disk.
     */
    last_open_ms: number | null;
    /**
     * Is this the book the session is holding? The one field here that is a
     * live fact rather than a scan result.
     */
    loaded: boolean;
    /**
     * The epub file name, which is what positions are keyed by.
     */
    name: string;
    /**
     * What those weigh, measured — not estimated.
     */
    packed_bytes: number;
    /**
     * Chapters with a *usable* packed m4a. A manifest that disagrees with the
     * plan is not one; see [`crate::library::scan_book`].
     */
    packed_chapters: number;
    /**
     * Absolute path on the server, or empty for a book whose audio is here and
     * whose source file is not.
     */
    path: string;
    position: null | StampedPosition;
    /**
     * Chapters every chunk of which was on disk at the scan. A chapter with no
     * chunks at all does not count: "nothing to render" is not "rendered".
     */
    rendered_chapters: number;
    rendered_chunks: number;
    title: string;
    total_chunks: number;
};

export type LibraryResult = {
    books: Array<LibraryBook>;
    /**
     * The **oldest** scan in this answer, so the reader can say how fresh it
     * is — and so one book that has not been walked since yesterday cannot hide
     * behind eleven that were walked a minute ago. Null when nothing in the
     * answer has ever been scanned.
     */
    scanned_ms: number | null;
};

export type LoadBody = {
    max_chars?: number | null;
    path: string;
};

export type LoadResult = {
    chapters: Array<ChapMeta>;
    /**
     * The cache directory name: the file stem, truncated to 50 characters.
     */
    key: string;
    position: null | StampedPosition;
    title: string;
    total_min: number;
};

export type Manifest = {
    bitrate: string;
    book: string;
    build_s: number;
    built: string;
    bytes: number;
    chapter: number;
    chunks: number;
    duration: number;
    gap: number;
    para_gap: number;
    sample_rate: number;
    /**
     * `starts[i]` is chunk `i`'s start second. `currentTime` maps back by
     * bisecting this.
     */
    starts: Array<number>;
    title: string;
};

export type NoteBody = {
    /**
     * base64 of the MediaRecorder blob.
     */
    audio: string;
    /**
     * The book the memo was recorded against, as a cache key. **Additive, and
     * worth sending**: a memo can wait out an offline stretch in the reader's
     * outbox and arrive after the server has loaded something else, and the
     * quote callout is built from a chapter's words. Supplied and not the
     * loaded book, the quote, frontmatter and deep link come from that book's
     * on-disk text bundle instead — no session swap, so whatever another device
     * is listening to is left alone. A key with no bundle on this server is a
     * **404**, never a 2xx, so the recording stays queued. Omitted, it means
     * "whatever is loaded", exactly as before.
     */
    book?: string | null;
    /**
     * Where the memo was recorded. Defaults to the session's own position.
     */
    chapter?: number | null;
    chunk?: number | null;
    /**
     * A stable id for this recording, so posting it twice files one note.
     * **Additive, and worth sending**: the reader only deletes its copy when it
     * sees the 2xx, and on a slow box the phone is often gone by then — so the
     * same memo arrives again. With an id, the second POST replays the first
     * one's answer instead of spending another multi-minute transcription and
     * filing a duplicate. Treated as a file name and ignored unless it is one;
     * omitted, the recording's own bytes identify it, which is what
     * deduplicates today's clients and the Obsidian plugin.
     */
    id?: string | null;
    mime?: string | null;
};

export type NoteResult = {
    /**
     * The note's file name in the vault.
     */
    file: string;
    language: string;
    ok: boolean;
    text: string;
};

/**
 * `{"ok": true}` plus whatever else a handler wants to say.
 */
export type Ok2 = {
    ok: boolean;
};

export type OpenBody = {
    /**
     * The book this is meant for. **Additive, and worth sending.** Playback is
     * one global session, so an open issued while the server holds a different
     * book moves the wrong book's render frontier and saves the position into
     * the wrong record. Supplied and mismatched, this is refused with a 409
     * instead; omitted, it means "whatever is loaded", exactly as before.
     */
    book?: string | null;
    chapter?: number;
    chunk?: number;
};

export type PauseResult = {
    ok: boolean;
    /**
     * Whether the renderer keeps filling the buffer while playback is stopped.
     */
    still_rendering: boolean;
};

export type PlayheadBody = {
    /**
     * See [`OpenBody::book`]: additive, and it stops a report meant for one
     * book from moving another one's frontier.
     */
    book?: string | null;
    chunk: number;
};

export type PositionBody = {
    book: string;
    chapter?: number | null;
    chapter_title?: string | null;
    chapters_total?: number | null;
    chunk?: number | null;
    chunks_total?: number | null;
};

export type PrerenderBody = {
    /**
     * Hours of estimated audio to build ahead. 0 or null falls back to the
     * static `PRERENDER_CHAPTERS`.
     */
    hours?: number | null;
};

export type PrerenderResult = {
    chapters_ahead: number;
    hours: number | null;
    ok: boolean;
};

export type RenderResult = {
    ok: boolean;
    /**
     * Chapters that were already complete and went straight to the packer.
     */
    packing: Array<number>;
    queue: Array<number>;
};

export type RendererBody = {
    on?: boolean;
};

export type RendererResult = {
    ok: boolean;
    rendering: boolean;
};

export type ShardChapter = {
    chunks: Array<string>;
    i: number;
    /**
     * What lets the reader re-form real paragraphs from chunks — a wall of
     * one-sentence blocks is not a page.
     */
    paras: Array<number>;
};

/**
 * A position as the *API* hands it back: the record above plus an unambiguous
 * instant.
 *
 * `updated` is a naive local stamp with no zone, because that is what the
 * python server writes into the vault and the file has to keep matching. A
 * browser cannot resolve it — a container without `/etc/localtime` stamps UTC
 * while the same reader's other positions are local, and the reader is left
 * guessing which of two positions is newer. So the API carries the instant as
 * well, resolved here where the server's own zone is known.
 */
export type StampedPosition = {
    chapter: number;
    chapter_title: string;
    chapters_total: number;
    chunk: number;
    chunks_total: number;
    /**
     * Naive local ISO, byte-identical to the vault record.
     */
    updated: string;
    /**
     * The same moment in epoch milliseconds. Null only if `updated` cannot be
     * parsed at all, which means it was not written by a narrator.
     */
    updated_ms?: number | null;
};

export type Status = {
    /**
     * `CHAPTER_BITRATE` as configured — `"64k"`. The reader multiplies a
     * chapter's estimated minutes by this to size a download before anything
     * has been packed; without it, it hard-codes the default and is silently
     * wrong by whatever ratio the box was set to.
     */
    bitrate: string;
    /**
     * The same number as bytes per minute of audio, so nobody has to parse the
     * suffix: `64k` → 480000.
     */
    bitrate_bytes_per_min: number;
    book: string | null;
    book_min: number | null;
    build_error: string | null;
    building: number | null;
    chapter: number;
    chapters: number;
    disk_cap_gb: number;
    disk_gb: number;
    done_min: number | null;
    error: string | null;
    key: string | null;
    model_ready: boolean;
    /**
     * What the packer is about to do, not only what it is doing. Without it a
     * chapter waiting to be packed looks idle.
     */
    pack_queue: Array<number>;
    pack_want: Array<number>;
    playhead: number;
    prerender: number | null;
    prerender_chapters: number;
    prerender_hours: number | null;
    prerender_span: number;
    queue: Array<number>;
    render_idx: number;
    rendered_min: number;
    rtf: number | null;
    status: string;
    title: string | null;
    total: number;
    voice: string;
};

export type TextShard = {
    chapters: Array<ShardChapter>;
    from: number;
    shard: number;
    to: number;
};

export type BookIndexData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * The cache key. Omitted, it means the loaded book.
         */
        book?: string | null;
    };
    url: '/api/book.json';
};

export type BookIndexErrors = {
    404: ApiError;
};

export type BookIndexError = BookIndexErrors[keyof BookIndexErrors];

export type BookIndexResponses = {
    200: BookIndex;
};

export type BookIndexResponse = BookIndexResponses[keyof BookIndexResponses];

export type BookIndex2Data = {
    body?: never;
    path?: never;
    query?: {
        /**
         * The cache key. Omitted, it means the loaded book.
         */
        book?: string | null;
    };
    url: '/api/book.json';
};

export type BookIndex2Errors = {
    404: ApiError;
};

export type BookIndex2Error = BookIndex2Errors[keyof BookIndex2Errors];

export type BookIndex2Responses = {
    200: BookIndex;
};

export type BookIndex2Response = BookIndex2Responses[keyof BookIndex2Responses];

export type BooksData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/books';
};

export type BooksResponses = {
    200: Array<BookFile>;
};

export type BooksResponse = BooksResponses[keyof BooksResponses];

export type ChapterData = {
    body?: never;
    path: {
        /**
         * chapter index
         */
        ci: number;
    };
    query?: {
        /**
         * The cache key. Omitted, it means the loaded book.
         */
        book?: string | null;
    };
    url: '/api/chapter/{ci}';
};

export type ChapterErrors = {
    404: ApiError;
};

export type ChapterError = ChapterErrors[keyof ChapterErrors];

export type ChapterResponses = {
    200: ChapterText;
};

export type ChapterResponse = ChapterResponses[keyof ChapterResponses];

export type ChaptersListData = {
    body?: never;
    path?: never;
    query?: {
        from?: number | null;
        to?: number | null;
        /**
         * The book the answer is meant to be about. Supplied and mismatched, the
         * response is a **409** rather than a confident description of the wrong
         * novel — which is what a poll that raced a book switch used to get, and
         * what the tap acting on it would then have aimed at.
         */
        book?: string | null;
    };
    url: '/api/chapters';
};

export type ChaptersListErrors = {
    /**
     * the session holds another book
     */
    409: ApiError;
};

export type ChaptersListError = ChaptersListErrors[keyof ChaptersListErrors];

export type ChaptersListResponses = {
    200: ChaptersResult;
};

export type ChaptersListResponse = ChaptersListResponses[keyof ChaptersListResponses];

export type ChaptersBuildData = {
    body: ChapterSetBody;
    path?: never;
    query?: never;
    url: '/api/chapters/build';
};

export type ChaptersBuildErrors = {
    400: ApiError;
    /**
     * the session holds another book
     */
    409: ApiError;
};

export type ChaptersBuildError = ChaptersBuildErrors[keyof ChaptersBuildErrors];

export type ChaptersBuildResponses = {
    200: BuildResult;
};

export type ChaptersBuildResponse = ChaptersBuildResponses[keyof ChaptersBuildResponses];

export type ChaptersCancelData = {
    body: ChapterSetBody;
    path?: never;
    query?: never;
    url: '/api/chapters/cancel';
};

export type ChaptersCancelErrors = {
    /**
     * the session holds another book
     */
    409: ApiError;
};

export type ChaptersCancelError = ChaptersCancelErrors[keyof ChaptersCancelErrors];

export type ChaptersCancelResponses = {
    200: CancelResult;
};

export type ChaptersCancelResponse = ChaptersCancelResponses[keyof ChaptersCancelResponses];

export type ChaptersRenderData = {
    body: ChapterSetBody;
    path?: never;
    query?: never;
    url: '/api/chapters/render';
};

export type ChaptersRenderErrors = {
    400: ApiError;
    /**
     * the session holds another book
     */
    409: ApiError;
};

export type ChaptersRenderError = ChaptersRenderErrors[keyof ChaptersRenderErrors];

export type ChaptersRenderResponses = {
    200: RenderResult;
};

export type ChaptersRenderResponse = ChaptersRenderResponses[keyof ChaptersRenderResponses];

export type ChapterManifestData = {
    body?: never;
    path: {
        ci: number;
    };
    query?: {
        /**
         * The cache key. Omitted, it means the loaded book.
         */
        book?: string | null;
    };
    url: '/api/chapters/{ci}.json';
};

export type ChapterManifestErrors = {
    404: ApiError;
};

export type ChapterManifestError = ChapterManifestErrors[keyof ChapterManifestErrors];

export type ChapterManifestResponses = {
    200: Manifest;
};

export type ChapterManifestResponse = ChapterManifestResponses[keyof ChapterManifestResponses];

export type ChapterManifest2Data = {
    body?: never;
    path: {
        ci: number;
    };
    query?: {
        /**
         * The cache key. Omitted, it means the loaded book.
         */
        book?: string | null;
    };
    url: '/api/chapters/{ci}.json';
};

export type ChapterManifest2Errors = {
    404: ApiError;
};

export type ChapterManifest2Error = ChapterManifest2Errors[keyof ChapterManifest2Errors];

export type ChapterManifest2Responses = {
    200: Manifest;
};

export type ChapterManifest2Response = ChapterManifest2Responses[keyof ChapterManifest2Responses];

export type ChapterHlsData = {
    body?: never;
    path: {
        ci: number;
    };
    query?: {
        /**
         * The cache key. Omitted, it means the loaded book.
         */
        book?: string | null;
    };
    url: '/api/chapters/{ci}.m3u8';
};

export type ChapterHlsErrors = {
    404: ApiError;
    500: ApiError;
};

export type ChapterHlsError = ChapterHlsErrors[keyof ChapterHlsErrors];

export type ChapterHlsResponses = {
    200: string;
};

export type ChapterHlsResponse = ChapterHlsResponses[keyof ChapterHlsResponses];

export type ChapterHls2Data = {
    body?: never;
    path: {
        ci: number;
    };
    query?: {
        /**
         * The cache key. Omitted, it means the loaded book.
         */
        book?: string | null;
    };
    url: '/api/chapters/{ci}.m3u8';
};

export type ChapterHls2Errors = {
    404: ApiError;
    500: ApiError;
};

export type ChapterHls2Error = ChapterHls2Errors[keyof ChapterHls2Errors];

export type ChapterHls2Responses = {
    200: string;
};

export type ChapterHls2Response = ChapterHls2Responses[keyof ChapterHls2Responses];

export type ChapterAudioData = {
    body?: never;
    path: {
        ci: number;
    };
    query?: {
        /**
         * The cache key. Omitted, it means the loaded book.
         */
        book?: string | null;
    };
    url: '/api/chapters/{ci}.m4a';
};

export type ChapterAudioErrors = {
    404: ApiError;
    /**
     * unsatisfiable range
     */
    416: unknown;
};

export type ChapterAudioError = ChapterAudioErrors[keyof ChapterAudioErrors];

export type ChapterAudioResponses = {
    200: Array<number>;
    /**
     * byte range
     */
    206: unknown;
};

export type ChapterAudioResponse = ChapterAudioResponses[keyof ChapterAudioResponses];

export type ChapterAudio2Data = {
    body?: never;
    path: {
        ci: number;
    };
    query?: {
        /**
         * The cache key. Omitted, it means the loaded book.
         */
        book?: string | null;
    };
    url: '/api/chapters/{ci}.m4a';
};

export type ChapterAudio2Errors = {
    404: ApiError;
    /**
     * unsatisfiable range
     */
    416: unknown;
};

export type ChapterAudio2Error = ChapterAudio2Errors[keyof ChapterAudio2Errors];

export type ChapterAudio2Responses = {
    200: Array<number>;
    /**
     * byte range
     */
    206: unknown;
};

export type ChapterAudio2Response = ChapterAudio2Responses[keyof ChapterAudio2Responses];

export type ChunkWavData = {
    body?: never;
    path: {
        ci: number;
        i: number;
    };
    query?: never;
    url: '/api/chunk/{ci}/{i}.wav';
};

export type ChunkWavErrors = {
    /**
     * not rendered yet
     */
    404: ApiError;
};

export type ChunkWavError = ChunkWavErrors[keyof ChunkWavErrors];

export type ChunkWavResponses = {
    200: Array<number>;
};

export type ChunkWavResponse = ChunkWavResponses[keyof ChunkWavResponses];

export type ChunkWav2Data = {
    body?: never;
    path: {
        ci: number;
        i: number;
    };
    query?: never;
    url: '/api/chunk/{ci}/{i}.wav';
};

export type ChunkWav2Errors = {
    /**
     * not rendered yet
     */
    404: ApiError;
};

export type ChunkWav2Error = ChunkWav2Errors[keyof ChunkWav2Errors];

export type ChunkWav2Responses = {
    200: Array<number>;
};

export type ChunkWav2Response = ChunkWav2Responses[keyof ChunkWav2Responses];

export type EventsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * This device's id. A query parameter rather than the `X-Narrator-Device` header every other endpoint takes, because `EventSource` cannot set request headers — and this is the endpoint that tells the server which devices are connected right now.
         */
        device?: string;
        /**
         * A label for that device, display only.
         */
        device_name?: string;
    };
    url: '/api/events';
};

export type EventsResponses = {
    /**
     * hello, then position/render/books/note events and heartbeats
     */
    200: string;
};

export type EventsResponse = EventsResponses[keyof EventsResponses];

export type HlsSegmentData = {
    body?: never;
    path: {
        book: string;
        ci: number;
        name: string;
    };
    query?: never;
    url: '/api/hls/{book}/{ci}/{name}';
};

export type HlsSegmentErrors = {
    404: ApiError;
};

export type HlsSegmentError = HlsSegmentErrors[keyof HlsSegmentErrors];

export type HlsSegmentResponses = {
    200: Array<number>;
};

export type HlsSegmentResponse = HlsSegmentResponses[keyof HlsSegmentResponses];

export type HlsSegment2Data = {
    body?: never;
    path: {
        book: string;
        ci: number;
        name: string;
    };
    query?: never;
    url: '/api/hls/{book}/{ci}/{name}';
};

export type HlsSegment2Errors = {
    404: ApiError;
};

export type HlsSegment2Error = HlsSegment2Errors[keyof HlsSegment2Errors];

export type HlsSegment2Responses = {
    200: Array<number>;
};

export type HlsSegment2Response = HlsSegment2Responses[keyof HlsSegment2Responses];

export type LibraryData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * One book's cache key. Unknown keys answer with an empty list rather than
         * a 404: this endpoint describes what is here, and "not here" is an answer.
         */
        book?: string | null;
        /**
         * Include the per-chapter rows. Only meaningful alongside `book`; it is
         * ignored for the all-books answer, which would otherwise be enormous.
         */
        chapters?: boolean | null;
    };
    url: '/api/library';
};

export type LibraryResponses = {
    200: LibraryResult;
};

export type LibraryResponse = LibraryResponses[keyof LibraryResponses];

export type LoadData = {
    body: LoadBody;
    path?: never;
    query?: never;
    url: '/api/load';
};

export type LoadErrors = {
    /**
     * the file is not a readable EPUB
     */
    400: ApiError;
};

export type LoadError = LoadErrors[keyof LoadErrors];

export type LoadResponses = {
    200: LoadResult;
};

export type LoadResponse = LoadResponses[keyof LoadResponses];

export type NoteData = {
    body: NoteBody;
    path?: never;
    query?: never;
    url: '/api/note';
};

export type NoteErrors = {
    /**
     * no book, no audio, or nothing heard
     */
    400: ApiError;
    /**
     * `book` names a book with no text bundle here, or - for an `id` sent with no audio, which asks whether that memo was filed - no note has been filed for it
     */
    404: ApiError;
    /**
     * transcription or the vault write failed
     */
    500: ApiError;
};

export type NoteError = NoteErrors[keyof NoteErrors];

export type NoteResponses = {
    /**
     * filed - the outbox may delete its copy. The same body comes back for a memo already filed under this `id`, so a retry the server has already answered costs nothing
     */
    200: NoteResult;
};

export type NoteResponse = NoteResponses[keyof NoteResponses];

export type OpenChapterData = {
    body: OpenBody;
    headers?: {
        /**
         * Who is reporting. Additive: omitted, this is the anonymous legacy device and the behaviour is exactly the pre-device one. Supplied, it is echoed on the `position` event so other devices can tell a real move from their own echo.
         */
        'X-Narrator-Device'?: string | null;
        /**
         * A human label for that device, for display only.
         */
        'X-Narrator-Device-Name'?: string | null;
    };
    path?: never;
    query?: never;
    url: '/api/open';
};

export type OpenChapterErrors = {
    /**
     * the session holds another book
     */
    409: ApiError;
};

export type OpenChapterError = OpenChapterErrors[keyof OpenChapterErrors];

export type OpenChapterResponses = {
    200: Ok2;
};

export type OpenChapterResponse = OpenChapterResponses[keyof OpenChapterResponses];

export type PauseData = {
    body?: never;
    headers?: {
        /**
         * Who is reporting. Additive: omitted, this is the anonymous legacy device and the behaviour is exactly the pre-device one. Supplied, it is echoed on the `position` event so other devices can tell a real move from their own echo.
         */
        'X-Narrator-Device'?: string | null;
        /**
         * A human label for that device, for display only.
         */
        'X-Narrator-Device-Name'?: string | null;
    };
    path?: never;
    query?: never;
    url: '/api/pause';
};

export type PauseResponses = {
    200: PauseResult;
};

export type PauseResponse = PauseResponses[keyof PauseResponses];

export type PlayheadData = {
    body: PlayheadBody;
    headers?: {
        /**
         * Who is reporting. Additive: omitted, this is the anonymous legacy device and the behaviour is exactly the pre-device one. Supplied, it is echoed on the `position` event so other devices can tell a real move from their own echo.
         */
        'X-Narrator-Device'?: string | null;
        /**
         * A human label for that device, for display only.
         */
        'X-Narrator-Device-Name'?: string | null;
    };
    path?: never;
    query?: never;
    url: '/api/playhead';
};

export type PlayheadErrors = {
    /**
     * the session holds another book
     */
    409: ApiError;
};

export type PlayheadError = PlayheadErrors[keyof PlayheadErrors];

export type PlayheadResponses = {
    200: Ok2;
};

export type PlayheadResponse = PlayheadResponses[keyof PlayheadResponses];

export type PositionData = {
    body: PositionBody;
    headers?: {
        /**
         * Who is reporting. Additive: omitted, this is the anonymous legacy device and the behaviour is exactly the pre-device one. Supplied, it is echoed on the `position` event so other devices can tell a real move from their own echo.
         */
        'X-Narrator-Device'?: string | null;
        /**
         * A human label for that device, for display only.
         */
        'X-Narrator-Device-Name'?: string | null;
    };
    path?: never;
    query?: never;
    url: '/api/position';
};

export type PositionErrors = {
    400: ApiError;
    500: ApiError;
};

export type PositionError = PositionErrors[keyof PositionErrors];

export type PositionResponses = {
    200: Ok2;
};

export type PositionResponse = PositionResponses[keyof PositionResponses];

export type PrerenderData = {
    body: PrerenderBody;
    path?: never;
    query?: never;
    url: '/api/prerender';
};

export type PrerenderErrors = {
    400: ApiError;
};

export type PrerenderError = PrerenderErrors[keyof PrerenderErrors];

export type PrerenderResponses = {
    200: PrerenderResult;
};

export type PrerenderResponse = PrerenderResponses[keyof PrerenderResponses];

export type RendererData = {
    body: RendererBody;
    path?: never;
    query?: never;
    url: '/api/renderer';
};

export type RendererResponses = {
    200: RendererResult;
};

export type RendererResponse = RendererResponses[keyof RendererResponses];

export type ResumeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/resume';
};

export type ResumeResponses = {
    200: Ok2;
};

export type ResumeResponse = ResumeResponses[keyof ResumeResponses];

export type StatusData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/status';
};

export type StatusResponses = {
    200: Status;
};

export type StatusResponse = StatusResponses[keyof StatusResponses];

export type BookTextData = {
    body?: never;
    path: {
        /**
         * shard index
         */
        s: number;
    };
    query?: {
        /**
         * The cache key. Omitted, it means the loaded book.
         */
        book?: string | null;
    };
    url: '/api/text/{s}.json';
};

export type BookTextErrors = {
    404: ApiError;
};

export type BookTextError = BookTextErrors[keyof BookTextErrors];

export type BookTextResponses = {
    200: TextShard;
};

export type BookTextResponse = BookTextResponses[keyof BookTextResponses];

export type BookText2Data = {
    body?: never;
    path: {
        /**
         * shard index
         */
        s: number;
    };
    query?: {
        /**
         * The cache key. Omitted, it means the loaded book.
         */
        book?: string | null;
    };
    url: '/api/text/{s}.json';
};

export type BookText2Errors = {
    404: ApiError;
};

export type BookText2Error = BookText2Errors[keyof BookText2Errors];

export type BookText2Responses = {
    200: TextShard;
};

export type BookText2Response = BookText2Responses[keyof BookText2Responses];

export type HealthzData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/healthz';
};

export type HealthzErrors = {
    /**
     * something that matters is wedged
     */
    503: Health;
};

export type HealthzError = HealthzErrors[keyof HealthzErrors];

export type HealthzResponses = {
    200: Health;
};

export type HealthzResponse = HealthzResponses[keyof HealthzResponses];
